[package]
name = "elebox"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "Lightweight personal electronic parts inventory management tool"
repository = "https://github.com/ziteh/elebox"
authors = ["ZiTe <honmonoh@gmail.com>"]
readme = "README.md"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
elebox-core = { path = "../../elebox-core" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
