name: Rust build & test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev

      - name: Print toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Build
        run: cargo build -p elebox-core --verbose

      - name: Run tests
        run: cargo test -p elebox-core --verbose
